The fix for the NULL ptr dereference was not correct as the if statement was not bracketed. I fixed that and did it slightly differently for style reasons.
Either way, the original fix has to go because it completely breaks -p.

Behavior with the original 'fix' for the NULL ptr deref behaves like this:

--- snip ---
$ sudo masscan -p 1 1.2.3.4
-p: empty parameter
ERROR: bad IP address/range: 1
FAIL: no ports were specified
[hint] try something like "-p80,8000-9000"
[hint] try something like "--ports 0-65535"
$ sudo bin/masscan "-p80,8000-9000" 1.2.3.4
FAIL: no ports were specified
[hint] try something like "-p80,8000-9000"
[hint] try something like "--ports 0-65535"
$ sudo bin/masscan -p80,8000-9000 1.2.3.4
FAIL: no ports were specified
[hint] try something like "-p80,8000-9000"
[hint] try something like "--ports 0-65535"
--- snip ---